### ISSUE TITLE
Zoom Level Smaller than 15

### ISSUE THREAD

**Issue by nasiryahm** [OSMBuildings/GLMap#2]
I seem to be having an issue in which, no matter what baselayer of tiles I use, I cannot zoom out beyond zoom level 14 without the screen becoming all white. There are no error messages and I have correctly set the maximum/minimum zoom levels (i.e. they work when I limit it to a range between 14 and 22).

Any ideas? Is this an inherent limitation? I'd love to be able to zoom out to a larger world view.

**Comment by nasiryahm** [comment]
Correction: Minimum Zoom level fourteen works - anything lower is white.

**Comment by rbuch703** [comment]
Yes, that is currently an inherent limitation. At coarser zoom levels we would have to load too much building geometry, and the algorithms that determine which map tiles to load and render are also not fit for coarser zoom levels.

**Comment by nasiryahm** [comment]
Interesting - Is the limit hardcoded? I am hoping to play around a little and was hoping you could point me in the right direction for enabling any zoom level. I am considering turning on and off building geometries at a given zoom level to help speed that part up and am curious to experiment.

**Comment by rbuch703** [comment]
That wouldn't help. We've also hard-coded the maximum distance from the camera that is still drawn at 7500m (the projection "far" plane), and the sky drawn in the background is about 5000m away from the camera. Both are set not arbitrarily, but to work around different technical limitations and therefore cannot easily be changed. So really you wouldn't get any useful results even if you could bypass the zoom limit.

**Comment by nasiryahm** [comment]
Ah, I did notice the far z-plane is fixed throughout. I'll work within the limit. Thanks for your time!
